### ISSUE TITLE
Comments for the example.py file?

### ISSUE THREAD

**Issue by darksipu** [wiseman/py-webrtcvad#10]
Hi there, 

I'm trying to use the example.py to output files where I've got speech as opposed to no speech. At the moment it outputs files at different intervals

Was wondering whether you have comments to attach to the file, to understand what some of the details in the vad_collector function, for example do, as I'm trying to tweak it a bit to get what I want.

Thanks, 
Florin

**Comment by wiseman** [comment]
I added some comments to example.py, let me know if those are sufficient.
