### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by YAIsaienkov** [wiseman/py-webrtcvad#13]
I get this error when try to install.
![image](https://user-images.githubusercontent.com/25550114/33784612-32b8edb0-dc6a-11e7-9cdc-51952e15969f.png)

**Comment by wiseman** [comment]
It looks like this is an [error in pip](https://github.com/pypa/pip/issues/4825).

(it's usually better to copy & paste error message text rather than paste screenshots, to help search engines with indexing and make it easier for other people to find solutions to their problems.)
