### ISSUE TITLE
Will this detect the speech segments in any scenario?

### ISSUE THREAD

**Issue by StanSilas** [wiseman/py-webrtcvad#14]
In case I have an audio with 
tring_tring ... hold music... speaker_1 ... speaker_2 ... ... speaker_1 .... hold_music end_of_conversation.  

If I were to pass the above above audio to this library,
Will this library ignore all music and extract just the speaker_1 speaker_2 segments? 
If so how is this to be accomplished?

**Comment by wiseman** [comment]
I think there's a good chance it will work, as long as the hold music doesn't contain singing or other speech.

You can try it by running the `example.py` script and giving it a sample audio file.
