### ISSUE TITLE
Why the result is different ?

### ISSUE THREAD

**Issue by yule2001** [wiseman/py-webrtcvad#15]
Dear Wiseman,
    When I use webrtcvad2.0.10 to detect some wav,I found the result is different when I comment the code 
```
    num_voiced = len([f for f in ring_buffer
                              if vad.is_speech(f.bytes, sample_rate)])
```
env:
centos6.5 Python 2.7.14

before comment:

000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

after comment:

000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001111100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by wiseman** [comment]
That line shouldn't have any effect on the number of `1`s (audio frame contains speech) or `0`s (audio frame does not contain speech) that are printed, so I don't know what's happening.  Maybe paste the entire function you're using?

(The `example.py` script does a version of "debouncing"--it only triggers if it sees a window of 10 audio frames where at least 9 are voiced, as determined by `vad.is_speech`.  In your "after comment" example, there are only 5 1's--5 30 millisecond frames that seem to contain speech.  That's a very short piece of speech, 150 milliseconds, so the original version of the script does not trigger.)

**Comment by yule2001** [comment]
Thanks for your reply. Code like this:  
     sys.stdout.write(
            '1' if vad.is_speech(frame.bytes, sample_rate) else '0')
        if not triggered:
            ring_buffer.append(frame)
            #num_voiced = len([f for f in ring_buffer
            #                  if vad.is_speech(f.bytes, sample_rate)])
            #if num_voiced > 0.9 * ring_buffer.maxlen:
            #    sys.stdout.write('+(%s)' % (ring_buffer[0].timestamp,))
            #    triggered = True
            #    voiced_frames.extend(ring_buffer)
            #    ring_buffer.clear()

**Comment by wiseman** [comment]
OK, I think the issue is that the VAD detector is stateful, and the loop in `example.py` calls `vad.is_speech` multiple times on each frame of audio.  I need to modify it to call `is_speech` only one time on each frame.

**Comment by wiseman** [comment]
Fixed.
