### ISSUE TITLE
Enhancement request - Limit audio file chunk sizes

### ISSUE THREAD

**Issue by jehoshua7** [wiseman/py-webrtcvad#16]
Python 3.5.2

Ran a few small tests today using **py-webrtcvad** with a 19 second WAV file. I'm impressed with the results as the output WAV's appear to respect what I will call 'word boundaries'. That is, words are not broken up on output.

Can an enhancement be made to limit the audio file chunk sizes, as the audio chunk files created were between 1 second and 48 seconds. Apparently smaller WAV files are required for training purposes in Speech Recognition.

**Comment by manbharae** [comment]
@jehoshua7  Could you tell how to process a .wav/.mp3 using py-webrtcvad? 
i.e After doing pip install py-webrtcvad what do I do?

**Comment by jehoshua7** [comment]
@manbharae - I remembered I had a permission error when installing, but this fixed it

`pip3 install --user webrtcvad`

and then to run it, set the aggressive mode and specify filename

`python3 example.py 0 output.wav`

for agressive mode of 0, and

`python3 example.py 1 output.wav`

for agressive mode of 1, etc.

**Comment by manbharae** [comment]
I too had the installation issue. your suggestion of `--user` tag helped! Thank you very much for pointing it :+1: .

Question: 
say my file is name test.wav
 in the `python3 example.py 1 output.wav` how does it know where to find `test.wav` to process?

**Comment by jehoshua7** [comment]
> how does it know where to find test.wav to process?

It's all relative. If your file test.wav is in the current path, it is

`python3 example.py 1 test.wav`

If your file test.wav is in some other path, it is

`python3 example.py 1 ~/someotherpath/output.wav`

**Comment by wiseman** [comment]
`example.py` is just meant to show you how to write code that uses the VAD, not be a full-featured application.  But you could try changing [line 150](https://github.com/wiseman/py-webrtcvad/blob/6ba97cdb84bfe1f6ca24bc94088ff54ab3621117/example.py#L150) to use a smaller time window.  Instead of 
```
segments = vad_collector(sample_rate, 30, 300, vad, frames)
```

try this, which changes the time window from 300 ms to 100 ms:

```
segments = vad_collector(sample_rate, 30, 100, vad, frames)
```

**Comment by jehoshua7** [comment]
@wiseman   Yes, thanks John, that was the line I was looking at last night. So, good timing, thanks.  :)

**Comment by sagar2226** [comment]
@jehoshua7  how can we get audio chunks size no more than 9 seconds?
