### ISSUE TITLE
Webrtcvad with sample width 1 instead of 2

### ISSUE THREAD

**Issue by stevemacn** [wiseman/py-webrtcvad#17]
I have an 8-bit recording but it seems like the webrtcvad only supports 16-bit recordings. Is there any way to get 8-bit recordings to work other than converting them to 16-bit representation?

**Comment by wiseman** [comment]
I don't think so, at least not with this version. The webrtc VAD code has changed a lot in the past year or two and I haven't really kept up to date, so it's possible a newer version has that capability--though I think it's unlikely, as 8-bit audio doesn't seem to be commonly used.

I'm curious, where is your 8-bit audio coming from?

**Comment by stevemacn** [comment]
Yeah, I was worried that would be the case. 

I am using lapel microphones to detect speech over the course of long recording sessions. They generate a lot of data and so 8-bit seemed to be a good way to save on bandwidth and processing time. I implemented a VAD algorithm which works well for many use-cases, but it isn't as robust to large variations in noise as I had hoped. I wanted to try the webrtc to see if that would address the issues.

Thank you so much! I'll circle back here if I find out anything useful

**Comment by wibimaster** [comment]
From : https://chromium.googlesource.com/external/webrtc/+/master/common_audio/vad/vad_core.c

`int WebRtcVad_CalcVad8khz(VadInstT* inst, const int16_t* speech_frame, size_t frame_length)`

;)
