### ISSUE TITLE
why divide duration by 2 in example.py

### ISSUE THREAD

**Issue by Liang-Qiu** [wiseman/py-webrtcvad#21]
Hi,
In frame_generator of example.py, why 
`n = int(sample_rate * (frame_duration_ms / 1000.0) * 2)
duration = (float(n) / sample_rate) / 2.0
`
It seems that the resulted timestamp will be half of the real timestamp. But the wierd thing is if I delete the *2 and /2.0, the webrtcvad can't process the frame.

**Comment by wiseman** [comment]
It's because the PCM audio data is in the form of 16-bit samples, so each sample takes 2 bytes, so 2 elements in the array.  If the sample rate is 16 KHz, in one second you would have 1 * 16000 * 2 = 32000 bytes worth of data.

**Comment by Liang-Qiu** [comment]
Thank you!
