### ISSUE TITLE
Is there some adaptive technique happening in the back stage?

### ISSUE THREAD

**Issue by fanwei918** [wiseman/py-webrtcvad#22]
I have been using py-webrtcvad for detecting existence of voice from many short clips. What I observe is, if I do in this way: (some pseudo code)

```
vad1 = webrtcvad.Vad()
for filename in files:
    have_voice.append ( process_by_vad1(filename) )
get_count_have_voice (have_voice)   
```

The count of files with voice derived is not same as this way:

```
for filename in files:
    vad1 = webrtcvad.Vad()
    have_voice.append ( process_by_vad1(filename) )
get_count_have_voice (have_voice)   
```

So, if I didn't screwed up something, I guess there is some adaptive things happens in vad class, so in the 1st way, some coefficients get tuned when I read in more and more files, hence in the final, the performance is different with the 2nd way. 

Is the assumption correct? 

Many Thanks.

**Comment by fanwei918** [comment]
Found that the indent is 

vad1 = webrtcvad.Vad()
for filename in files:
have_voice.append ( process_by_vad1(filename) )
get_count_have_voice ()

**Comment by wiseman** [comment]
The VAD algorithm used by this code is not described in any detail by Google, but I assume that it is adapting its model as it is fed audio input.
