### ISSUE TITLE
is_speech returns 1 even when there is just noise and no speech in the attached wav file

### ISSUE THREAD

**Issue by ppatali** [wiseman/py-webrtcvad#24]
I am running example.py as it is on my Windows 10 machine with Python 3.6. The sample wav file being used is extracted from a video recorded on a phone. There is no speech frames in this 8 seconds audio but still the output from the example.py is exactly like the input and seem to mark most of the frames as is_speech = 1. I am puzzled as the output should have not marked any frame as speech! Could there be some issue with this wav file? 

Sample wav file  [11.wav](https://drive.google.com/file/d/10SRJDyLUg1M3aK9ffxUfCTKqcC9mi6h-/view?usp=sharing)

Executed with params -
_example.py 3 11.wav_

Terminal output is as below:
00001111111111+(0.12)1111111111111111111111111110111111111111111111111011100111101111111111111111111011110000000011111111111111111111111111111111111111111111111111101111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111-(8.280000000000015) 
Writing chunk-00.wav

**Comment by ppatali** [comment]
If you listen to 11.wav, you will notice there is continuous background noise. This was recorded within a car when driving on a freeway. There are no spoken words in the entire clip.

I tried with another sample recording, in a closed room with my laptop microphone. In this case example.py successfully detected the frames with voice parts. 

I guess WebRTC is unable to detect and filter out the background noise in case of 11.wav.

**Comment by wiseman** [comment]
It seems like this is an issue with WebRTC itself, and not the python wrapper.  One thing you could try is modifying this code to use the latest version of WebRTC.
