### ISSUE TITLE
where is the _webrtcvad module

### ISSUE THREAD

**Issue by andreaschandra** [wiseman/py-webrtcvad#25]
I found something unusual in webrtcvad.py, in the 3rd line says `import _webrtcvad` but i couldn't find any folder or file that is named _webrtcvad. can you tell me where, so i could know what `_webrtcvad.process()` do

**Comment by wiseman** [comment]
The _webrtcvad module is a C extension module (which gets compiled when you install webrtcvad).  The process function is defined here: https://github.com/wiseman/py-webrtcvad/blob/master/cbits/pywebrtcvad.c#L85
