### ISSUE TITLE
System Crash

### ISSUE THREAD

**Issue by sarkarsaikat** [wiseman/py-webrtcvad#26]
Hi All,
I get a system crush when ever I try to execute this line:
frames = frame_generator(30, audio, sample_rate)
frames = list(frames)

It seems frames = list(frames) takes up all the RAM (16 GB)

Please advice

**Comment by wiseman** [comment]
It sounds like you're trying to process a very large file.  Do you need to create a list of frames, or can you process them frame-by-frame and avoid the memory overhead of creating all the required frames at once?

**Comment by wiseman** [comment]
Closing this since there hasn't been an update.
