### ISSUE TITLE
Voiced frames duration

### ISSUE THREAD

**Issue by ropok** [wiseman/py-webrtcvad#35]
Hello, how to decide the duration of the voiced frames?
Because for now the result is to short..

I want to make it longer, like 1 second of silence then the voice appear and then 1 second of silence in the ending.

**Comment by jonnor** [comment]
One approach is to post-process the VAD output. If you want 1 second gaps at the start and end, subtract 1 second from start time, and add one second to the end time. This is called padding.
This might end up with overlapping regions, which you may want to merge into one region.

Another common post-processing is to merge regions which are very close to eachother. For example to merge regions that are less than 1 seconds apart into one region.
