### ISSUE TITLE
[start time, end time] of extracted segments

### ISSUE THREAD

**Issue by mohammad-saber** [wiseman/py-webrtcvad#37]
Thanks a lot for sharing your code.

I would like to know how I can get the [start time, end time] data of extracted segments. I am running "example.py".

**Comment by zgoda-mobica** [comment]
Set start timestamp to 1st voiced frame start on entering triggered state, set end timestamp to last voiced frame start + frame duration on leaving triggered state.

**Comment by snakers4** [comment]
this feature is supported by this vad - https://github.com/snakers4/silero-vad
