### ISSUE TITLE
Why is there a variation in output with various audio readers?

### ISSUE THREAD

**Issue by meghana1697** [wiseman/py-webrtcvad#38]
Hi, 
 I had been trying to read the various .wav files with different python libraries. I tried using wave as you did and also tried librosa, ffmpeg and soundfile. But with different libraries i am getting different number of chunks in the output. Can you please explain why is it that VAD works the best when we use wave reader over the other audio readers.

**Comment by wiseman** [comment]
Hm, I have no idea. Sorry!  All I can think of is that you try dumping the decoded PCM data from each reader and see if it's really the same.

**Comment by meghana1697** [comment]
> def read_wave(path):
>     '''data, sample_rate = librosa.core.load(path, sr=16000)
>     pcm_data = np.ndarray.tobytes(data)'''
>     with contextlib.closing(wave.open(path, 'r')) as wf:
>         sample_rate = wf.getframerate()
>         frames = wf.getnframes()
>         pcm_data = wf.readframes(frames)
>     return pcm_data, sample_rate

This is what i tried to read a file. I used those quoted lines when reading using librosa. On using librosa for reading audio and a 5 min 51 sec audio file I got two chunks with 5 min 30 sec and 20 sec durations. Whereas when i us the wave reader i got 63 files as output.

**Comment by wiseman** [comment]
I think you may want to compare the PCM data read by the two different methods to see if it's the same (as I said in my first comment). Write the PCM data you get from librosa method to a file, and write the PCM data from the wave reader to a file. Try using sox to play the data, e.g. `sox play -t raw -r 16k -e signed -b 16 -c 1 librosa.raw`.

This sounds more like it's a librosa issue than a py-webrtcvad issue, though, so I'm going to close this bug.  Sorry I couldn't be more help.
