### ISSUE TITLE
example.py does not return/specify the start-time of each segment in the original input wave file

### ISSUE THREAD

**Issue by r-soroosh** [wiseman/py-webrtcvad#4]
Hi John,

The example.py segments a wave file to different segments. I am interested to know/extract the start/stop time of each segment within the wave file. For example, the the second segment start-time is exactly at which second in the original input wave file.

Thanks in advance,
Soroosh

**Comment by wiseman** [comment]
I've committed a change to `example.py` so it now prints the start and end times of each voiced segment.

```
$ python example.py 3 ~/test.wav 
00000011111110+(0.24)1111111111111111111111111111111111111111111100000000-(3.96) Writing chunk-00.wav
00000000011111111+(4.38)1111111111111111111111111111000000-(7.02) Writing chunk-01.wav
000
```

For example, in the run above, chunk-00.wav contains audio from 00:00.24 to 00:03.96 and chunk-01.wav contains audio from 00:04.38 to 00:07.02.

**Comment by r-soroosh** [comment]
Thanks John for updating the example.
