### ISSUE TITLE
Question about perfomance

### ISSUE THREAD

**Issue by DevJhns** [wiseman/py-webrtcvad#43]
Hello @wiseman  thx for awesome interface! 
I just want to know, how much it hit perfomance, if I send audio to server and detecting speech 100 times per second it's not heavy task, but what if I have 200 users, and this will be 20000 requests per second + calculations, isn't it too much? How many cpu server should have to handle this? Or better to do it on client side in this case thx!

**Comment by wiseman** [comment]
I don't know, my code is just a python wrapper around Google's webrtc code.
