### ISSUE TITLE
Get vad score

### ISSUE THREAD

**Issue by marialaraa** [wiseman/py-webrtcvad#44]
Is it possible to get the vad score? I mean, to delete this lines: 

https://github.com/wiseman/py-webrtcvad/blob/3b39545dbb026d998bf407f1cb86e0ed6192a5a6/cbits/webrtc/common_audio/vad/webrtc_vad.c#L86-L88

I would like to set a custom threshold to consider that there is speech or not. 

Thanks!

**Comment by snakers4** [comment]
this feature is supported by this vad - https://github.com/snakers4/silero-vad
