### ISSUE TITLE
Functional Description of Algorithm

### ISSUE THREAD

**Issue by schmiph2** [wiseman/py-webrtcvad#46]
Hi Py-WebrtcVAD-Team

Thank you for wrapping the webrtcvad. Everything worked straightforward and the algo had a pretty good performance. I want to integrate the algorithm in an embedded solution. As i'm already calculating features related to the log-power of the six bands used by the VAD on my device, I am interested in the detailed design of the algorithm to adapt it to my features. Have you any description? Like a paper or a flowchart? What I found out from the code is, that some sort of adaptive GMM (sequential EM?) is involved. Do you have any further information?

Thank you in advance?

**Comment by wiseman** [comment]
Hello!  The VAD code is by Google, and the last time I checked they gave no description of what the code does beyond comments in the code. Sorry!
