### ISSUE TITLE
How does ASR determine output?

### ISSUE THREAD

**Issue by jhoelzl** [wiseman/py-webrtcvad#5]
Hello,

i am looking for an VAD that does not only count the energy level in a frame, but also incorporates voice/unvoiced segments (for example filter the frequency bands used for voice and compare the energy level to frequency bands that are not used for voice)

When i use this library (with 10, 20 or 30ms frames) and i tap on my microphone, the VAD returns `true`. Is there a way to overcome this?

Is there documentation available about the VAD processing insights?

Thanks,
Josef

**Comment by wiseman** [comment]
Ji, Josef. I believe the webrtc VAD looks at energy in different frequency bands over time, not just the total energy level in a frame.

In my experience, it will sometimes report false positives when it is first used (like from tapping on a microphone), but it seems to tune itself and give better results once it hears actual voice audio.

You could also try changing the aggressiveness parameter.

I'm not aware of any documentation on the webrtc VAD.  Most of what I've learned about it I got from reading comments in the [official source code](https://chromium.googlesource.com/external/webrtc/+/master/webrtc/common_audio/vad/).
