### ISSUE TITLE
sample rate

### ISSUE THREAD

**Issue by bbrookie** [wiseman/py-webrtcvad#54]
When I use the program in the example to process the audio of 44100 sampling rate, the program will report an error。

sample rate:44100
Traceback (most recent call last):
  File "vad2.py", line 143, in <module>
    main()
  File "vad2.py", line 138, in main
    filter(in_wav, out_dir, expand=False)
  File "vad2.py", line 118, in filter
    voiced_frames = vad_collector(sample_rate, vad, frames)
  File "vad2.py", line 87, in vad_collector
    is_speech = vad.is_speech(frame.bytes, sample_rate)
  File "/home/tian/anaconda3/envs/torch14/lib/python3.7/site-packages/webrtcvad.py", line 27, in is_speech
    return _webrtcvad.process(self._vad, sample_rate, buf, length)
webrtcvad.Error: Error while processing frame

And I want to know whether this tool can handle 44100 sample rate audio. I'm looking forward to your reply, thanks.

**Comment by wiseman** [comment]
It can't.  From the README:

> The WebRTC VAD only accepts 16-bit mono PCM audio, sampled at 8000, 16000, 32000 or 48000 Hz. A frame must be either 10, 20, or 30 ms in duration

I think a newer version of the WebRTC library that this Python wrapper uses can handle different sample rates, you could check that.
