### ISSUE TITLE
White noise detected as voice

### ISSUE THREAD

**Issue by kangaro0** [wiseman/py-webrtcvad#60]
Hey,

I'm trying out your package and I noticed that a recording only consisting of white noise gets detected as voiced.
I'm cutting the whole recording in n frames (10ms, 16kHz, mono) and process them with a for-loop ( like in the example-file ).

Can you give me a hint on why this is happening? 

King regards,
kangaro0

**Comment by snakers4** [comment]
Please give a try to silero-vad as well
We posted a comparison here - https://github.com/wiseman/py-webrtcvad/issues/68
