### ISSUE TITLE
README correction - also supports 48kHz

### ISSUE THREAD

**Issue by jgraniero** [wiseman/py-webrtcvad#7]
I was looking at the source and noticed that the chromium webrtc vad library also supports 48kHz audio, which is not mentioned in the README.

Might save some headaches if you add it to the README and the test for valid sample rates.

Edit: probably should've included a [link to the source](https://github.com/wiseman/py-webrtcvad/blob/master/cbits/webrtc/common_audio/vad/webrtc_vad.c#L21) in case I'm misunderstanding something.

**Comment by wiseman** [comment]
Thanks for the info!
