### ISSUE TITLE
I am having Issue installing webrtcvad i have posted the error code bellow

### ISSUE THREAD

**Issue by NvidiaShadowClone** [wiseman/py-webrtcvad#73]
(voice) E:\Real-Time-Voice-Cloning>pip install webrtcvad
Collecting webrtcvad
  Using cached webrtcvad-2.0.10.tar.gz (66 kB)
Building wheels for collected packages: webrtcvad
  Building wheel for webrtcvad (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Tony\anaconda3\envs\voice\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tony\\AppData\\Local\\Temp\\pip-install-d72smcli\\webrtcvad_e80b0fb060a8452199b5fa1adf378550\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tony\\AppData\\Local\\Temp\\pip-install-d72smcli\\webrtcvad_e80b0fb060a8452199b5fa1adf378550\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Tony\AppData\Local\Temp\pip-wheel-8s5sillb'
       cwd: C:\Users\Tony\AppData\Local\Temp\pip-install-d72smcli\webrtcvad_e80b0fb060a8452199b5fa1adf378550\
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  copying webrtcvad.py -> build\lib.win-amd64-3.7
  running build_ext
  building '_webrtcvad' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for webrtcvad
  Running setup.py clean for webrtcvad
Failed to build webrtcvad
Installing collected packages: webrtcvad
    Running setup.py install for webrtcvad ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Tony\anaconda3\envs\voice\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tony\\AppData\\Local\\Temp\\pip-install-d72smcli\\webrtcvad_e80b0fb060a8452199b5fa1adf378550\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tony\\AppData\\Local\\Temp\\pip-install-d72smcli\\webrtcvad_e80b0fb060a8452199b5fa1adf378550\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tony\AppData\Local\Temp\pip-record-renm8z7h\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Tony\anaconda3\envs\voice\Include\webrtcvad'
         cwd: C:\Users\Tony\AppData\Local\Temp\pip-install-d72smcli\webrtcvad_e80b0fb060a8452199b5fa1adf378550\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying webrtcvad.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_webrtcvad' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Tony\anaconda3\envs\voice\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tony\\AppData\\Local\\Temp\\pip-install-d72smcli\\webrtcvad_e80b0fb060a8452199b5fa1adf378550\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tony\\AppData\\Local\\Temp\\pip-install-d72smcli\\webrtcvad_e80b0fb060a8452199b5fa1adf378550\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tony\AppData\Local\Temp\pip-record-renm8z7h\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Tony\anaconda3\envs\voice\Include\webrtcvad' Check the logs for full command output.
WARNING: You are using pip version 21.2.2; however, version 21.2.3 is available.
You should consider upgrading via the 'C:\Users\Tony\anaconda3\envs\voice\python.exe -m pip install --upgrade pip' command.

**Comment by NvidiaShadowClone** [comment]
nvrmind i fixed it, i was being stupid.

**Comment by utmcontent** [comment]
How do you solve the problem?
